language: go
sudo: required

services:
  - docker
 
before_install:
  - docker build -t registry.heroku.com/"$HEROKU_NAME"/web .
  - docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" registry.heroku.com
  - docker push registry.heroku.com/"$HEROKU_NAME"/web
